name: Fetch latests CGC posts
on:
  schedule:
    - cron: "0 10 * * *" # Runs once a day at 10:00 UTC / 3:00 AM MST
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/fetch-blog-posts.yaml"
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull CGC RSS feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.chaoticgood.computer/index.xml"
          max_post_count: 5
          committer_username: "cgc-rss[bot]"
          committer_email: "blog@chaoticgood.computer"
          template: "$newline- **[$title]($url)**: $description$newline  - **Tags**: $categories$newline"
          item_exec: >-
            post.categories = post.categories.map(cat => {
              const label = cat.split('/').pop();
              return '[`#' + label + '`](https://blog.chaoticgood.computer/tags/' + cat + '/)';
            });
